### ISSUE TITLE
GarageSecurity not starting up - 

### ISSUE THREAD

**Issue by DervMan** [deckerego/GarageSecurity#20]
When trying to open the door I'm seeing a wiringpi GPIO error. Version  WebIOPi-0.7.1.

`root@raspberrypi:/srv/garagesec# python run_server.py
Bottle v0.12.9 server starting up (using WSGIRefServer())...
Listening on http://localhost:9003/
Hit Ctrl-C to quit.

127.0.0.1 - - [14/Jul/2016 12:33:12] "GET / HTTP/1.1" 200 2229
127.0.0.1 - - [14/Jul/2016 12:33:14] "GET /installed/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 304 0
127.0.0.1 - - [14/Jul/2016 12:33:14] "GET /installed/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 304 0
127.0.0.1 - - [14/Jul/2016 12:33:14] "GET /installed/jquery/dist/jquery.min.js HTTP/1.1" 304 0
127.0.0.1 - - [14/Jul/2016 12:33:14] "GET /css/styles.css HTTP/1.1" 304 0
127.0.0.1 - - [14/Jul/2016 12:33:14] "GET /js/mjpeg_viewer.js HTTP/1.1" 304 0
127.0.0.1 - - [14/Jul/2016 12:33:14] "GET /installed/bootstrap/dist/css/bootstrap-theme.min.css HTTP/1.1" 304 0
127.0.0.1 - - [14/Jul/2016 12:33:15] "GET /js/events.js HTTP/1.1" 304 0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/srv/garagesec/HIH6130.py", line 53, in wrapper
    rv = callback(*args, **kwargs)
  File "/srv/garagesec/routes.py", line 86, in get_environment
    humidity, celsius, status = temperature.get_conditions()
  File "/srv/garagesec/HIH6130.py", line 65, in get_conditions
    self.bus.write_quick(self.address)
IOError: [Errno 110] Connection timed out
127.0.0.1 - - [14/Jul/2016 12:33:18] "GET /environment HTTP/1.1" 500 751
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
TypeError: get_lastevent() takes exactly 1 argument (0 given)
127.0.0.1 - - [14/Jul/2016 12:33:18] "GET /lastevent HTTP/1.1" 500 749
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
TypeError: get_silence() takes exactly 1 argument (0 given)
127.0.0.1 - - [14/Jul/2016 12:33:18] "GET /alerts HTTP/1.1" 500 746
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/srv/garagesec/routes.py", line 149, in read_light_switch
    state = "true" if gpio.read_switch(switch) else "false"
  File "/srv/garagesec/gpio.py", line 38, in read_switch
    **io = wiringpi.GPIO(wiringpi.GPIO.WPI_MODE_SYS)**
AttributeError: type object 'GPIO' has no attribute 'WPI_MODE_SYS'
127.0.0.1 - - [14/Jul/2016 12:33:18] "GET /light/0 HTTP/1.1" 500 747
127.0.0.1 - - [14/Jul/2016 12:33:18] "GET /favicon.ico HTTP/1.1" 200 2686

`

**Comment by deckerego** [comment]
Will work on converting the project to the latest build of Raspian

**Comment by deckerego** [comment]
I was unable to reproduce on a brand-new build from master using the latest from Raspian. Can you confirm you are running the latest?
